---
- name: 'Get all snapshots with labels: "{{ label_selector }}"'
  delegate_to: "{{ delegation }}"
  register: response
  hetzner.hcloud.hcloud_image_info:
    api_token: "{{ hcloud_token }}"
    type: snapshot
    label_selector: "{{ label_selector }}"
  failed_when: response.hcloud_image_info | length == 0

- name: Get snapshots to delete for {{ inventory_hostname }}
  delegate_to: "{{ delegation }}"
  set_fact:
    delete_list: "{{ response.hcloud_image_info[0:response.hcloud_image_info | length - keep_snapshots | int] }}"
  when: response.hcloud_image_info | length - keep_snapshots | int > 0

- name: 'Delete {{ delete_list | length }} old snapshots for {{ inventory_hostname }}'
  delegate_to: "{{ delegation }}"
  when: delete_list | length > 0
  loop: "{{ delete_list }}"
  uri:
    url: "https://api.hetzner.cloud/v1/images/{{ item.id }}"
    method: DELETE
    status_code: 204
    headers:
      Authorization: "Bearer {{ hcloud_token }}"
