---
- name: Validate variables
  include_tasks: validate.yml

- name: Create {{ backup_type }}
  include_tasks: backup.yml

- name: Rotate snapshots
  when: backup_type == "snapshot" and rotate_snapshots == true
  include_tasks: rotate-snapshots.yml
