---
- name: Prepare label selector filter
  set_fact:
    label_selector_string: "{{ label_selector | items | map('join', '%3D') | join('%2C') }}"

- name: Get number of pages for snapshots that match the label selector
  delegate_to: "{{ delegation }}"
  register: response
  uri:
    url: "https://api.hetzner.cloud/v1/images?type=snapshot&per_page=50&status=available&label_selector={{ label_selector_string }}"
    method: GET
    status_code: 200
    headers:
      Authorization: "Bearer {{ api_token }}"

- name: Gather all snapshots that match the label selector
  delegate_to: "{{ delegation }}"
  register: response
  uri:
    url: "https://api.hetzner.cloud/v1/images?type=snapshot&per_page=50&status=available&label_selector={{ label_selector_string }}&page={{ item }}"
    method: GET
    status_code: 200
    headers:
      Authorization: "Bearer {{ api_token }}"
  loop: "{{ range(1, response.json.meta.pagination.last_page + 1) | list }}"

- name: "Prepare list of snapshots"
  set_fact:
    images: "{{ response.results | map(attribute='json.images') | flatten | selectattr('created_from.name', 'equalto', inventory_hostname) }}"

- name: Gather snapshots to delete
  delegate_to: "{{ delegation }}"
  set_fact:
    delete_list: "{{ images[0:images | length - keep_snapshots | int] }}"
  when: images | length - keep_snapshots | int > 0

- name: Show number of snapshots to delete
  debug:
    msg: "{{ delete_list | length }} of {{ images | length }} snapshots will be deleted"
  when: delete_list | length > 0

- name: "Delete old snapshots"
  delegate_to: "{{ delegation }}"
  when: delete_list | length > 0
  loop: "{{ delete_list }}"
  uri:
    url: "https://api.hetzner.cloud/v1/images/{{ item.id }}"
    method: DELETE
    status_code: 204
    headers:
      Authorization: "Bearer {{ api_token }}"
